-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Mutation exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias UpsertCommentRequiredArguments =
    { lineno : Int
    , sha : String
    , text : String
    }


upsertComment : UpsertCommentRequiredArguments -> SelectionSet decodesTo Api.Object.Comment -> SelectionSet (Maybe decodesTo) RootMutation
upsertComment requiredArgs object_ =
    Object.selectionForCompositeField "upsertComment" [ Argument.required "lineno" requiredArgs.lineno Encode.int, Argument.required "sha" requiredArgs.sha Encode.string, Argument.required "text" requiredArgs.text Encode.string ] object_ (identity >> Decode.nullable)
