-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type Change
    = Change


type Comment
    = Comment


type Commit
    = Commit


type Diff
    = Diff


type GitCommit
    = GitCommit


type GitCommitPerson
    = GitCommitPerson


type Organization
    = Organization


type Repository
    = Repository


type User
    = User
