-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Change exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


sha : SelectionSet String Api.Object.Change
sha =
    Object.selectionForField "String" "sha" [] Decode.string


filename : SelectionSet String Api.Object.Change
filename =
    Object.selectionForField "String" "filename" [] Decode.string


additions : SelectionSet Int Api.Object.Change
additions =
    Object.selectionForField "Int" "additions" [] Decode.int


deletions : SelectionSet Int Api.Object.Change
deletions =
    Object.selectionForField "Int" "deletions" [] Decode.int


changes : SelectionSet Int Api.Object.Change
changes =
    Object.selectionForField "Int" "changes" [] Decode.int


blobUrl : SelectionSet String Api.Object.Change
blobUrl =
    Object.selectionForField "String" "blobUrl" [] Decode.string


rawUrl : SelectionSet String Api.Object.Change
rawUrl =
    Object.selectionForField "String" "rawUrl" [] Decode.string


contentsUrl : SelectionSet String Api.Object.Change
contentsUrl =
    Object.selectionForField "String" "contentsUrl" [] Decode.string


patch : SelectionSet String Api.Object.Change
patch =
    Object.selectionForField "String" "patch" [] Decode.string
