-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Comment exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


sha : SelectionSet String Api.Object.Comment
sha =
    Object.selectionForField "String" "sha" [] Decode.string


lineno : SelectionSet Int Api.Object.Comment
lineno =
    Object.selectionForField "Int" "lineno" [] Decode.int


author : SelectionSet decodesTo Api.Object.User -> SelectionSet decodesTo Api.Object.Comment
author object_ =
    Object.selectionForCompositeField "author" [] object_ identity


text : SelectionSet String Api.Object.Comment
text =
    Object.selectionForField "String" "text" [] Decode.string
