-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.GitCommit exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


url : SelectionSet String Api.Object.GitCommit
url =
    Object.selectionForField "String" "url" [] Decode.string


author : SelectionSet decodesTo Api.Object.GitCommitPerson -> SelectionSet decodesTo Api.Object.GitCommit
author object_ =
    Object.selectionForCompositeField "author" [] object_ identity


committer : SelectionSet decodesTo Api.Object.GitCommitPerson -> SelectionSet decodesTo Api.Object.GitCommit
committer object_ =
    Object.selectionForCompositeField "committer" [] object_ identity


message : SelectionSet String Api.Object.GitCommit
message =
    Object.selectionForField "String" "message" [] Decode.string
